[package]
name = "slsswag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="6.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
regex = "1.5"
