name: "tagged-release"

on:
  push:
    tags:
      - "v*-windows"

jobs:

  tagged-release-windows:
    name: "Windows"
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build --release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE.txt
            ./target/release/slsswag.exe